<?php

function vpm_module_theme($existing, $type, $theme, $path)
{
    return [
        'vpm-index-artistas' => [
            'variables' => [
                'artistas' => []
            ]
        ],
        'vpm-index-catalogos' => [
            'variables' => [
                'catalogos' => []
            ]
        ],
        'vpm-index-tematicas' => [
            'variables' => [
                'tematicas' => []
            ]
        ],
        'vpm-vista-artista' => [
            'variables' => [
                'artista' => [], 'obrasDestacadas' => []
            ]
        ],
        'artistas' => [
            'variables' => [
                'artistas' => []
            ]
        ],
        'vpm-vista-catalogos-razonados' => [
            'variables' => [
                'catalogos' => []
            ]
        ],
        'vpm-vista-catalogo' => [
            'variables' => [
                'catalogo' => []
            ]
        ],
        'vpm-vista-sobreinvestigacion' => [
            'variables' => [
                'sobreinvestigacion' => []
            ]
        ],
        'vpm-vista-equipoinvestigacion' => [
            'variables' => [
                'equipoinvestigacion' => []
            ]
        ],
        'vpm-vista-preguntasfrecuentes' => [
            'variables' => [
                'preguntasfrecuentes' => []
            ]
        ],
        'vpm-catalogo-menu' => [
            'variables' => [
                'links' => []
            ]
        ],
        'vpm-catalogo-relacionados' => [
            'variables' => [
                'links' => []
            ]
        ],
        'vpm-vista-obra' => [
            'variables' => [
                'obra' => []
            ]
        ],
        'vpm-vista-obras' => [
            'variables' => [
                'obras' => [],
                'arrayBoton' => [],
                'tematica' => [],
                'annio' => [],
                'artista' => [],
                'idCat' => null,
                'Sec' => null,
                'busquedaIndex' => null,
                'ordenarPor' => 0,
                'tecnica' => []
            ]
        ],
        'vpm-vista-publicaciones' => [
            'variables' => [
                'publicaciones' => [],
                'arrayBoton' => []
            ]
        ],
        'vpm-vista-publicacion' => [
            'variables' => [
                'publicacion' => []
            ]
        ],
        'vpm-vista-pdf' => [
            'variables' => [
                'obra' => []
            ]
        ],
        'vpm-vista-pdfprueba' => [
            'variables' => [
                'obra' => []
            ]
        ],
        'vpm-vista-cronografia' => [
            'variables' => [
                'cronografia' => null
            ]
        ],
        'vpm-vista-grafico' => [
            'variables' => [
                'grafico' => [],
                'ordenaX' => 0,
                'ordenaY' => 0,
                'tematica' => [],
                'annio' => [],
                'artista' => [],
                'tecnica' => [],
            ]
        ],
    ];
}

// Aquí se definen las variables que se enviarán a la vista del modulo custom
// Estas son las mismas que se envian en el controlador (se puede ver al final del archivo)
